char *Words[][2] = {
    {"absurd", "불합리한"},
    {"abort", "유산하다"},
    {"accord", "일치하다"},
    {"adverse", "거꾸로의"},
    {"amplify", "확대하다"},
    {"archive", "기록보관소"},
    {"assault", "습격"},
    {"bishop", "주교"},
    {"blast", "돌풍"},
    {"breed", "기르다"},
    {"brute", "야수 짐승같은"},
    {"caption", "표제"},
    {"cater", "음식물을 마련하다"},
    {"chamber", "방"},
    {"chronic", "만성의"},
    {"compel", "억지로 -시키다"},
    {"compile", "편찬하다"},
    {"condemn", "나무라다"},
    {"confer", "주다"},
    {"consent", "승낙하다"},
    {"contend", "싸우다"},
    {"convert", "바꾸다"},
    {"county", "주"},
    {"creek", "시내"},
    {"creep", "기다"},
    {"curse", "저주"},
    {"custody", "보호"},
    {"cynical", "냉소적인"},
    {"decent", "점잖은"},
    {"deficit", "결손"},
    {"degrade", "지위를 낮추다"},
    {"depict", "묘사하다"},
    {"deposit", "예금"},
    {"deprive", "빼앗다"},
    {"dictate", "받아쓰게 하다"},
    {"dignity", "위엄"},
    {"dispute", "논쟁하다"},
    {"disrupt", "분열시키다"},
    {"distort", "찌그러뜨리다"},
    {"divine", "신의"},
    {"draft", "초고"},
    {"drain", "배수하다"},
    {"dread", "두려워하다 두려움"},
    {"embrace", "포옹하다"},
    {"enforce", "실시하다"},
    {"enroll", "명부에 올리다"},
    {"entitle", "자격을 주다"},
    {"equate", "같게하다"},
    {"erect", "똑바로 선"},
    {"estate", "토지"},
    {"ethical", "도덕상의"},
    {"ethnic", "인종의"},
    {"extract", "뽑아내다"},
    {"faculty", "능력"},
    {"fatal", "치명적인"},
    {"federal", "연방의"},
    {"fertile", "비옥한"},
    {"fluid", "유동성의"},
    {"flush", "왈칵흐르다"},
    {"formula", "공식"},
    {"foster", "기르다"},
    {"frost", "서리"},
    {"furious", "노하여 펄펄뛰는"},
    {"furnish", "공급하다"},
    {"glare", "번쩍이는 빛"},
    {"glimpse", "흘끗 봄"},
    {"grasp", "붙잡다"},
    {"gross", "총계의"},
    {"habitat", "(동물의)자연번식지"},
    {"haunt", "자주가다"},
    {"hence", "그러므로"},
    {"hostage", "볼모"},
    {"hostile", "반대하는"},
    {"immense", "무한한"},
    {"imply", "함축하다"},
    {"impose", "부과하다"},
    {"incline", "기울이다"},
    {"index", "색인"},
    {"induce", "꾀다"},
    {"infect", "감염시키다"},
    {"infer", "추론하다"},
    {"inflate", "부풀게 하다"},
    {"inhibit", "금하다"},
    {"inquire", "묻다"},
    {"lease", "임대차"},
    {"literal", "문자의"},
    {"merge", "합병하다"},
    {"migrate", "이주하다"},
    {"modest", "겸손한"},
    {"modify", "변경하다"},
    {"mortal", "죽을운명의"},
    {"mutual", "상호의"},
    {"naive", "소박한"},
    {"nanny", "유모"},
    {"nasty", "불쾌한"},
    {"notion", "관념"},
    {"oblige", "(의무를)별수없이 -하게하다"},
    {"obsess", "늘러붙다"},
    {"orbit", "궤도"},
    {"ounce", "삵괭이"},
    {"outrage", "불법(적인 행위)"},
    {"panel", "판벽널"},
    {"patch", "깁는 헝겊"},
    {"patent", "전매특허권 전매특허의"},
    {"patrol", "순회"},
    {"peasant", "농부"},
    {"persist", "고집하다"},
    {"phase", "국면"},
    {"pinch", "꼬집다"},
    {"pitch", "던지다"},
    {"polish", "닦다, 갈다, 윤내다"},
    {"portion", "일부, 부분"},
    {"preach", "설교하다"},
    {"precede", "-에 앞서다"},
    {"premier", "국무 총리, 수상"},
    {"premium", "할증금,  액면 초과액, 프리미엄"},
    {"presume", "가정하다"},
    {"prevail", "이기다, 극복하다, 압도하다 우세하다, 보급되다"},
    {"prior", "이전의, 앞의"},
    {"profile", "옆 얼굴, 반면상 인물 소개  태도, 자세"},
    {"prompt", "재빠른, 신속한, 즉시 …하는"},
    {"prosper", "번영하다"},
    {"provoke", "화나게 하다"},
    {"quote", "인용하다"},
    {"rally", "규합하다"},
    {"rebel", "반역자"},
    {"recruit", "신병"},
    {"refine", "정제정련하다"},
    {"reside", "거주하다"},
    {"resign", "사임하다"},
    {"resume", "다시 잡다"},
    {"retail", "소매"},
    {"retain", "보유하다"},
    {"retreat", "후퇴"},
    {"revenge", "복수"},
    {"reverse", "역"},
    {"salon", "객실"},
    {"scarce", "부족한"},
    {"scatter", "뿔뿔이 흩어 버리다"},
    {"scope", "범위"},
    {"screw", "나사"},
    {"scrub", "(관목의)숲"},
    {"seize", "붙잡다"},
    {"shelter", "피난처"},
    {"shield", "방패"},
    {"shrink", "줄어들다"},
    {"slight", "약간의"},
    {"slope", "비탈"},
    {"sneak", "몰래 움직이다"},
    {"sniff", "코를 킁킁거리다"},
    {"sphere", "구"},
    {"spill", "엎지르다"},
    {"spite", "악의"},
    {"splash", "튀기다"},
    {"split", "쪼개다"},
    {"spouse", "배우자"},
    {"stack", "낟가리"},
    {"starve", "굶어 죽다"},
    {"steep", "가파른 -에 담그다 잠기다 담그기"},
    {"stiff", "굳은"},
    {"stitch", "한 바늘"},
    {"strain", "잡아당기다"},
    {"strip", "벗기다"},
    {"stroke", "한번치기"},
    {"submit", "복종시키다"},
    {"subtle", "미묘한"},
    {"suite", "수행원"},
    {"suspend", "매달다"},
    {"sustain", "떠받치다"},
    {"swear", "맹세하다"},
    {"sweep", "청소하다"},
    {"swell", "부풀다"},
    {"swift", "빠른"},
    {"tease", "괴롭히다"},
    {"tempt", "유혹하다"},
    {"tenant", "차지인"},
    {"terrace", "계단모양의 뜰(광장)"},
    {"testify", "증명하다"},
    {"therapy", "치료법"},
    {"thread", "실"},
    {"timber", "재목"},
    {"torture", "고문"},
    {"trail", "질질 끌다"},
    {"treaty", "조약"},
    {"trigger", "방아쇠 재빠른"},
    {"undergo", "(영향 등을)받다"},
    {"utilize", "-을 이용하다"},
    {"utter", "전적인"},
    {"vague", "막연한"},
    {"valid", "유효한"},
    {"vanish", "자취를 감추다"},
    {"verbal", "말의, 말에 관한, 언어상의, 말로 나타낸, 말로 된"},
    {"verse", "시의 한 줄, 시구  일련의 시구"},
    {"vessel", "그릇"},
    {"veteran", "노련가, 경험 많은 대가, 베테랑"},
    {"virgin", "처녀, 동정녀, 미혼 여성, 동정녀 마리아"},
    {"virtual", "사실상의, 실질상의, 실제의  허상의"},
    {"virtue", "덕, 덕행, 선, 선행"},
    {"vital", "생명의, 생명에 관한, 생명유지에 필요한, 살아 있는"},
    {"vivid", "발랄한, 약동적인, 힘찬, 생기있는"},
    {"wagon", "짐마차"},
    {"wander", "헤매다"},
    {"warrant", "보증하다 보증"},
    {"warrior", "병사"},
    {"weave", "짜다"},
    {"whereas", "(-인)까닭에"},
    {"wicked", "사악한"},
    {"widow", "미망인"},
    {"wreck", "난파"},
    {"yield", "산출하다"},
    {"abandon", "버리다"},
    {"aboard", "배로"},
    {"abroad", "외국으로"},
    {"absent", "부재의"},
    {"absorb", "흡수하다"},
    {"abuse", "남용"},
    {"accept", "받아들이다"},
    {"access", "접근"},
    {"account", "설명하다 계산"},
    {"accuse", "고발하다"},
    {"achieve", "성취하다"},
    {"acquire", "얻다"},
    {"actual", "현실의"},
    {"acute", "날카로운"},
    {"adapt", "적용시키다"},
    {"addict", "열중하게 하다"},
    {"adjust", "맞추다"},
    {"admire", "감복하다"},
    {"admit", "받아들이다"},
    {"adopt", "채용하다"},
    {"advance", "나아가다"},
    {"affair", "일"},
    {"affect", "영향을 주다"},
    {"afford", "여유가 있다"},
    {"agency", "기능"},
    {"agenda", "안건"},
    {"agent", "대리인"},
    {"aisle", "측면복도"},
    {"alert", "빈틈없는"},
    {"alien", "외국의"},
    {"alike", "비슷한"},
    {"alive", "살아있는"},
    {"allow", "허락하다"},
    {"alter", "바꾸다"},
    {"amaze", "깜짝 놀라게 하다"},
    {"among", "-중에"},
    {"amount", "(금액이)-이 되다"},
    {"amuse", "재미나게 하다"},
    {"analyze", "분해하다"},
    {"anchor", "닻"},
    {"ancient", "옛날의"},
    {"angle", "각"},
    {"annoy", "귀찮게하다"},
    {"annual", "일년의"},
    {"anxiety", "근심"},
    {"anxious", "걱정되는"},
    {"apart", "떨어져서"},
    {"apology", "사과"},
    {"appeal", "간청하다"},
    {"appear", "나타나다"},
    {"apply", "(물건을)대다"},
    {"appoint", "지정하다"},
    {"approve", "시인하다"},
    {"argue", "논하다"},
    {"arise", "생기다"},
    {"arrange", "가지런히 하다"},
    {"arrest", "체포하다"},
    {"arrow", "화살"},
    {"article", "물품"},
    {"aside", "곁에"},
    {"asleep", "잠들은"},
    {"aspect", "관점"},
    {"aspire", "열망하다"},
    {"assert", "단언하다"},
    {"assess", "(세금 등을)사정하다"},
    {"asset", "자산"},
    {"assign", "할당하다"},
    {"assist", "돕다"},
    {"assume", "취하다"},
    {"assure", "보증하다"},
    {"athlete", "운동가"},
    {"attach", "붙이다"},
    {"attack", "공격하다"},
    {"attain", "이르다"},
    {"attempt", "시도하다"},
    {"attend", "출석하다"},
    {"attract", "끌어 당기다"},
    {"auction", "경매"},
    {"author", "저자"},
    {"avenue", "가로수길"},
    {"average", "평균"},
    {"avoid", "피하다"},
    {"await", "기다리다"},
    {"awake", "깨우다"},
    {"award", "상"},
    {"aware", "알고 있는"},
    {"awesome", "무서운"},
    {"awful", "두려운"},
    {"awkward", "어색한"},
    {"balance", "균형"},
    {"bargain", "매매"},
    {"barrier", "장벽"},
    {"basis", "기초"},
    {"beard", "턱수염"},
    {"beast", "짐승"},
    {"behalf", "위함"},
    {"behave", "행동하다"},
    {"belong", "속하다"},
    {"beneath", "-의 바로 아래에"},
    {"benefit", "이익"},
    {"berry", "액과"},
    {"betray", "배반하다"},
    {"beyond", "저편에"},
    {"bible", "성서, 성경"},
    {"billion", "10억"},
    {"biology", "생물학"},
    {"bitter", "쓴"},
    {"blame", "책망하다"},
    {"blank", "공백"},
    {"blanket", "담요"},
    {"blend", "혼합하다"},
    {"bless", "축복하다"},
    {"blind", "눈먼"},
    {"blink", "(눈을)깜빡거리다"},
    {"blonde", "(살결이 흰)금발의 여성"},
    {"bloom", "쇳덩이"},
    {"blossom", "(과수의)꽃"},
    {"boost", "뒤를 밀기"},
    {"border", "가장자리"},
    {"bother", "괴롭히다 근심하다 귀찮음"},
    {"bounce", "뛰어오르다"},
    {"breast", "가슴"},
    {"breathe", "숨쉬다"},
    {"breeze", "미풍"},
    {"brick", "벽돌"},
    {"bride", "신부"},
    {"brief", "단시간의"},
    {"broad", "(폭이)넓은"},
    {"budget", "예산"},
    {"bullet", "탄환"},
    {"bully", "약한 자를 못살게 구는 자"},
    {"bunch", "송이"},
    {"bundle", "다발"},
    {"burden", "후렴"},
    {"burst", "파열하다"},
    {"butcher", "정육점주인"},
    {"cabin", "선실"},
    {"cable", "해저전신"},
    {"cancel", "취소하다"},
    {"cancer", "암"},
    {"canvas", "돛베"},
    {"capable", "할 수 있는"},
    {"capital", "수위의"},
    {"capture", "붙잡다(=catch)"},
    {"career", "경력"},
    {"carve", "조각하다"},
    {"casual", "우연한"},
    {"cattle", "소"},
    {"causal", "원인의"},
    {"cause", "원인"},
    {"caution", "조심"},
    {"cease", "그만두다 그치다 중지"},
    {"ceiling", "천장"},
    {"censor", "검열관"},
    {"century", "1세기"},
    {"chaos", "혼돈"},
    {"charge", "요금"},
    {"charity", "자비"},
    {"charm", "매력"},
    {"chase", "쫓다"},
    {"cheek", "볼"},
    {"cheer", "갈채"},
    {"chest", "가슴팍"},
    {"chief", "우두머리"},
    {"chill", "차가움"},
    {"choir", "(교회의)성가대"},
    {"chorus", "합창"},
    {"citizen", "시민"},
    {"civil", "시민의"},
    {"claim", "요구하다"},
    {"clarify", "맑게 하다"},
    {"clash", "충돌하다"},
    {"classic", "고전의"},
    {"clause", "조항"},
    {"client", "소송의뢰인"},
    {"cliff", "절벽"},
    {"climate", "기후"},
    {"cling", "밀착하다"},
    {"clinic", "병원"},
    {"cluster", "떼"},
    {"coach", "역마차"},
    {"coast", "연안"},
    {"collar", "칼라"},
    {"colony", "식민지"},
    {"column", "(신문 등의)난"},
    {"combat", "격투하다"},
    {"combine", "결합하다"},
    {"comfort", "위안"},
    {"command", "명령하다"},
    {"comment", "논평"},
    {"commit", "위탁하다"},
    {"compare", "비교하다"},
    {"compete", "경쟁하다"},
    {"complex", "합성물"},
    {"compose", "구성하다"},
    {"conceal", "숨기다"},
    {"concept", "개념"},
    {"concern", "관계하다"},
    {"conduct", "행위 이끌다"},
    {"confess", "실토하다"},
    {"confine", "국경"},
    {"confirm", "확인하다"},
    {"conform", "일치시키다"},
    {"confuse", "혼란시키다"},
    {"connect", "잇다 이어지다"},
    {"consist", "-으로 이루어지다"},
    {"consult", "상의하다"},
    {"consume", "소비하다"},
    {"contact", "접촉"},
    {"contain", "내포하다"},
    {"content", "만족하여"},
    {"context", "문맥"},
    {"convey", "나르다"},
    {"convict", "유죄로 판결하다 죄수"},
    {"correct", "옳은"},
    {"corrupt", "타락한"},
    {"costume", "복장"},
    {"cottage", "시골집"},
    {"couch", "침대"},
    {"cough", "기침, 기침을 하다"},
    {"council", "회의"},
    {"counsel", "의논"},
    {"count", "계산"},
    {"counter", "계산하는 사람"},
    {"courage", "용기"},
    {"cowboy", "목동"},
    {"crack", "찰싹 소리내다, 금가다, 날카로운소리"},
    {"craft", "솜씨"},
    {"crash", "도산"},
    {"crawl", "네발로 기다"},
    {"create", "창조하다"},
    {"credit", "신용"},
    {"cricket", "크리켓"},
    {"crime", "범죄"},
    {"crisis", "위기"},
    {"crisp", "파삭파삭한"},
    {"critic", "비평가"},
    {"crucial", "결정적인"},
    {"cruel", "잔인한"},
    {"cruise", "순항하다"},
    {"crush", "눌러 부수다"},
    {"crystal", "수정"},
    {"current", "유행의"},
    {"curry", "카레요리, 카레로 맛을 내다"},
    {"curve", "곡선"},
    {"custom", "습관"},
    {"dairy", "낙농장"},
    {"damage", "손해"},
    {"darling", "귀여운"},
    {"debate", "토론 토론하다"},
    {"decade", "10년간"},
    {"decay", "쇠퇴하다"},
    {"declare", "선언하다"},
    {"decline", "기울다"},
    {"defeat", "패배"},
    {"defense", "방어"},
    {"defend", "방어하다"},
    {"define", "정의하다"},
    {"degree", "도, 각도"},
    {"delay", "늦추다"},
    {"delete", "삭제하다"},
    {"delight", "즐겁게하다 즐거워하다"},
    {"deliver", "인도하다"},
    {"demand", "요구하다"},
    {"demon", "악마"},
    {"dense", "짙은"},
    {"depend", "좌우되다"},
    {"depress", "억압하다"},
    {"derive", "이끌어 내다"},
    {"descend", "내려오다"},
    {"desert", "버리다"},
    {"deserve", "-할 만하다"},
    {"desire", "바라다"},
    {"despair", "절망하다"},
    {"despite", "-에도 불구하고 모욕"},
    {"destiny", "운명"},
    {"destroy", "파괴하다"},
    {"detach", "분리하다"},
    {"detail", "상설"},
    {"detect", "간파하다"},
    {"develop", "발달하다"},
    {"device", "고안"},
    {"devil", "악마"},
    {"devise", "고안하다"},
    {"devote", "바치다"},
    {"direct", "지도하다"},
    {"disease", "병"},
    {"disgust", "불쾌하게 하다"},
    {"dismiss", "떠나게 하다"},
    {"display", "보이다"},
    {"dispose", "배열하다"},
    {"distant", "떨어진"},
    {"disturb", "교란하다"},
    {"diverse", "다양한"},
    {"divorce", "이혼"},
    {"domain", "영토"},
    {"donate", "증여하다"},
    {"doubt", "의심"},
    {"dozen", "1다스"},
    {"drawer", "제도사"},
    {"drown", "물에빠뜨리다"},
    {"dwell", "거주하다"},
    {"dynamic", "동적인"},
    {"eager", "열심인"},
    {"economy", "절약"},
    {"educate", "교육하다"},
    {"effect", "결과"},
    {"effort", "노력"},
    {"either", "어느 하나의"},
    {"elect", "선거하다"},
    {"elegant", "우아한"},
    {"element", "요소"},
    {"embassy", "대사관"},
    {"emerge", "나오다"},
    {"emotion", "감정"},
    {"empire", "제국"},
    {"employ", "고용하다"},
    {"empty", "빈"},
    {"enclose", "에워싸다"},
    {"endure", "견디다"},
    {"enemy", "적"},
    {"engage", "약속하다"},
    {"enhance", "향상하다"},
    {"ensure", "-을 책임지다"},
    {"entire", "전체의"},
    {"entry", "들어감"},
    {"episode", "삽화"},
    {"equal", "같은"},
    {"escape", "도망하다"},
    {"escort", "호위하다"},
    {"evident", "명백한"},
    {"evolve", "진화하다"},
    {"exact", "정확한"},
    {"examine", "시험하다"},
    {"exceed", "넘다"},
    {"except", "-을 제외하고는 제외하다"},
    {"excess", "초과"},
    {"excite", "흥분시키다"},
    {"exclude", "배척하다"},
    {"excuse", "변명"},
    {"exhaust", "다 써버리다"},
    {"exhibit", "보이다"},
    {"exist", "존재하다"},
    {"exotic", "외국의"},
    {"expand", "펴다"},
    {"expect", "기대하다"},
    {"expense", "지출"},
    {"expert", "숙련가"},
    {"explain", "설명하다"},
    {"explode", "폭발시키다"},
    {"explore", "탐험하다"},
    {"export", "수출하다 수출"},
    {"expose", "쐬다, 드러내다, 맞히다"},
    {"express", "발표하다"},
    {"extend", "뻗다"},
    {"extent", "넓이"},
    {"extinct", "꺼진"},
    {"extra", "가외의"},
    {"extreme", "극단의"},
    {"eyebrow", "눈썹"},
    {"fabric", "천"},
    {"factor", "요소"},
    {"faint", "기절하다"},
    {"faith", "신용"},
    {"false", "거짓"},
    {"fancy", "공상"},
    {"fasten", "단단히 고정시키다"},
    {"fault", "결점"},
    {"favor", "호의"},
    {"feature", "얼굴의 생김새"},
    {"fellow", "동무"},
    {"female", "여성"},
    {"ferry", "나루터"},
    {"fiber", "섬유"},
    {"fierce", "흉포한"},
    {"figure", "모습"},
    {"filter", "여과기 여과하다"},
    {"final", "최후의"},
    {"finance", "재정"},
    {"finite", "한정되어 있는"},
    {"flame", "불꽃"},
    {"flash", "번쩍임"},
    {"flavor", "(독특한)맛"},
    {"flesh", "살"},
    {"flight", "날기"},
    {"float", "뜨다"},
    {"flock", "무리"},
    {"flood", "홍수"},
    {"follow", "쫓다"},
    {"forbid", "금하다"},
    {"force", "힘"},
    {"foreign", "외국의"},
    {"forgive", "용서하다"},
    {"formal", "형식상의"},
    {"format", "(서적의)체제"},
    {"former", "이전의"},
    {"forth", "앞으로"},
    {"fortune", "운"},
    {"forum", "공개토론회"},
    {"forward", "앞쪽에"},
    {"frame", "구조"},
    {"frankly", "솔직히"},
    {"freeze", "얼다"},
    {"fright", "(갑자기 엄습하는)공포"},
    {"frown", "눈살을 찌푸리다"},
    {"fulfil", "이행하다"},
    {"funeral", "장사"},
    {"gamble", "도박하다 도박 도박해서 잃다"},
    {"garage", "차고"},
    {"gather", "그러모으다"},
    {"gender", "성"},
    {"general", "일반적인"},
    {"genius", "천재"},
    {"genre", "유형"},
    {"gentle", "온화한"},
    {"genuine", "진짜의"},
    {"geology", "지질학"},
    {"glance", "흘긋 봄"},
    {"global", "공모양의"},
    {"glory", "영광"},
    {"goods", "상품"},
    {"govern", "다스리다"},
    {"grace", "은총"},
    {"grade", "등급"},
    {"gradual", "점차적인"},
    {"grain", "곡물"},
    {"grand", "위대한"},
    {"grant", "받아들이다"},
    {"graphic", "그려 놓은 듯한"},
    {"grave", "무덤"},
    {"greed", "탐욕"},
    {"greet", "인사하다"},
    {"grief", "심한 슬픔"},
    {"grocery", "식품잡화류"},
    {"guest", "손님"},
    {"guilty", "죄지은"},
    {"hammer", "망치"},
    {"handle", "손잡이"},
    {"happen", "(사건 등이)일어나다"},
    {"harbor", "항구"},
    {"hardly", "거의 -아니다"},
    {"harsh", "거친"},
    {"harvest", "수확"},
    {"haste", "급함"},
    {"hazard", "위험"},
    {"health", "건강"},
    {"height", "높이"},
    {"highway", "대도"},
    {"honor", "명예"},
    {"horizon", "지평선"},
    {"horror", "공포"},
    {"ideal", "이상"},
    {"ignore", "무시하다"},
    {"imagine", "상상하다"},
    {"imitate", "흉내내다"},
    {"immune", "면역성의"},
    {"impact", "충격"},
    {"import", "수입하다"},
    {"impress", "인상지우다"},
    {"improve", "개선하다"},
    {"include", "포함하다"},
    {"income", "수입"},
    {"indeed", "참으로"},
    {"infant", "유아"},
    {"inform", "알리다"},
    {"inhabit", "살다"},
    {"initial", "처음의"},
    {"inject", "주사하다"},
    {"injure", "해치다"},
    {"input", "투입"},
    {"insect", "곤충"},
    {"insert", "끼워넣다"},
    {"insight", "통찰(력)"},
    {"insist", "주장하다"},
    {"inspect", "검사하다"},
    {"inspire", "영감을 주다"},
    {"install", "설치하다"},
    {"instant", "즉시의"},
    {"instead", "그 대신에"},
    {"insult", "모욕하다"},
    {"insure", "보증하다"},
    {"intend", "-할 작정이다"},
    {"intense", "강렬한"},
    {"intent", "의향"},
    {"invade", "침입하다"},
    {"invent", "발명하다"},
    {"invest", "투자하다"},
    {"involve", "말아넣다"},
    {"irony", "반어"},
    {"island", "섬"},
    {"isolate", "고립시키다"},
    {"joint", "이음매"},
    {"journal", "일간신문"},
    {"journey", "여행"},
    {"judge", "재판관"},
    {"junior", "손아래사람"},
    {"justice", "정의"},
    {"justify", "옳다고 하다"},
    {"knight", "(중세의)기사"},
    {"knock", "치다"},
    {"label", "라벨"},
    {"labor", "노동"},
    {"ladder", "사닥다리"},
    {"latter", "뒤쪽의"},
    {"laugh", "(소리내어)웃다"},
    {"launch", "진수시키다"},
    {"laundry", "세탁물"},
    {"lawyer", "법률가"},
    {"layer", "층"},
    {"leather", "무두질한 가죽"},
    {"leave", "남기고가다"},
    {"lecture", "강의"},
    {"legal", "법률상의"},
    {"legend", "전설"},
    {"leisure", "틈"},
    {"level", "수평의"},
    {"liberal", "자유주의의"},
    {"liberty", "자유"},
    {"license", "면허"},
    {"likely", "있을 법한"},
    {"limit", "한계"},
    {"liquid", "액체"},
    {"local", "장소의"},
    {"locate", "관청 등을 두다"},
    {"logic", "논리학"},
    {"loose", "풀어진"},
    {"lounge", "빈둥거리다"},
    {"loyal", "충성스러운"},
    {"luxury", "사치"},
    {"machine", "기계"},
    {"magnet", "자석"},
    {"major", "큰쪽의"},
    {"manage", "관리하다"},
    {"manner", "방법"},
    {"margin", "가장자리"},
    {"marine", "바다의"},
    {"marvel", "경이"},
    {"master", "장"},
    {"match", "성냥"},
    {"matter", "물질"},
    {"mature", "익은"},
    {"maximum", "최고점"},
    {"maybe", "아마"},
    {"mayor", "시장"},
    {"measure", "재다"},
    {"mediate", "중재하다"},
    {"medical", "의학의"},
    {"medium", "중간"},
    {"mental", "마음의"},
    {"mention", "말하다"},
    {"merit", "장점"},
    {"metal", "금속"},
    {"method", "방법"},
    {"million", "백만"},
    {"miner", "광산업자"},
    {"mineral", "광물"},
    {"minimal", "최소(한도)의"},
    {"minimum", "최소 한도"},
    {"minor", "작은 편의"},
    {"minute", "분"},
    {"miracle", "기적"},
    {"missile", "미사일"},
    {"mission", "사명"},
    {"mistake", "틀리다"},
    {"mobile", "움직이기 쉬운"},
    {"modern", "현대의"},
    {"moment", "순간"},
    {"monitor", "충고자"},
    {"monster", "괴물"},
    {"moral", "도덕의"},
    {"motion", "운동"},
    {"motive", "동기"},
    {"mount", "산"},
    {"murder", "살인"},
    {"muscle", "근육"},
    {"naked", "발가벗은"},
    {"narrate", "이야기하다"},
    {"narrow", "좁은"},
    {"native", "타고난"},
    {"needle", "바늘, 바느질하다, 아슬아슬한"},
    {"neglect", "게을리 하다"},
    {"neither", "(둘중)어느쪽도 -아니다 -도 아니다"},
    {"nephew", "조카"},
    {"nervous", "신경의"},
    {"network", "그물세공"},
    {"neutral", "중립의"},
    {"noble", "고귀한"},
    {"nobody", "아무도 -않다 하찮은 사람"},
    {"noise", "소리"},
    {"normal", "표준(의)"},
    {"notice", "통지, 통보"},
    {"novel", "소설"},
    {"nowhere", "아무데도 …없다"},
    {"nuclear", "핵의, 핵을 형성하는 원자핵의"},
    {"object", "사물"},
    {"observe", "관찰하다"},
    {"obtain", "얻다"},
    {"obvious", "명백한"},
    {"occupy", "차지하다"},
    {"occur", "일어나다"},
    {"offend", "성나게 하다"},
    {"offer", "권하다"},
    {"officer", "공무원"},
    {"olive", "올리브나무"},
    {"operate", "움직이다"},
    {"opinion", "의견"},
    {"oppose", "반대하다"},
    {"option", "선택(권의 자유)"},
    {"order", "순서"},
    {"organ", "(생물의)기관"},
    {"organic", "유기체의"},
    {"orient", "동양 동양의 동쪽으로 향하게 하다"},
    {"origin", "기원"},
    {"other", "다른 다른 것 그렇지 않고"},
    {"ought", "해야만 하다"},
    {"outcome", "결과"},
    {"outline", "윤곽"},
    {"output", "산출"},
    {"overall", "포괄(전면)적인 덧옷"},
    {"overlap", "겹치다"},
    {"oversea", "해외(로부터)의"},
    {"packet", "다발"},
    {"panic", "돌연한공포"},
    {"pardon", "용서하다 용서"},
    {"passage", "통행, 통과"},
    {"passion", "정열"},
    {"patient", "인내심이 강한 환자"},
    {"pattern", "모범"},
    {"pause", "중지"},
    {"penalty", "벌"},
    {"pepper", "고추"},
    {"perfect", "완전한"},
    {"perform", "다하다"},
    {"perhaps", "아마"},
    {"period", "시간"},
    {"permit", "허가하다"},
    {"person", "사람"},
    {"phrase", "구"},
    {"physics", "물리학"},
    {"piece", "한 조각"},
    {"pioneer", "개척자"},
    {"plain", "분명한"},
    {"planet", "행성"},
    {"plant", "실물"},
    {"plate", "판"},
    {"plenty", "많음"},
    {"poison", "독"},
    {"polar", "남극의"},
    {"policy", "정책"},
    {"polite", "공손한"},
    {"pollute", "-을 더럽히다"},
    {"popular", "민중 의, 대중의"},
    {"possess", "소유하다"},
    {"poster", "포스터"},
    {"powder", "가루"},
    {"praise", "칭찬"},
    {"precise", "정확한"},
    {"predict", "예언하다, 예보하다 예언하다"},
    {"prefer", "오히려 …을 좋아하다,"},
    {"prepare", "준비하 다, 마련하다, 채비를 갖추다"},
    {"press", "강제로 모집하다"},
    {"pretend", "핑계삼다"},
    {"prevent", "막다, 방해하다"},
    {"price", "값, 가격, 대가, 정가"},
    {"pride", "자존심"},
    {"priest", "성직자"},
    {"primary", "첫째의, 제1위의, 수위의 초등의, 초보의"},
    {"prime", "수위의, 최초의, 원시적인"},
    {"prison", "교도소"},
    {"privacy", "남의 눈을 피함, 은거, 은둔, 은퇴 생활 사생활"},
    {"private", "사적인, 사사로운, 개인에 속한"},
    {"proceed", "나아가다, 가다"},
    {"process", "진행, 작용"},
    {"produce", "생산하다, 산출하다, 생기게 하다,"},
    {"profit", "이익, 이득, 벌이"},
    {"promise", "약속, 서약, 계약"},
    {"promote", "승진시키다 진행시키다,"},
    {"proof", "증명"},
    {"proper", "고유의, 독특한, 본연의,  특유한"},
    {"propose", "제의하다, 제출하다 추천하다, 지명하다"},
    {"protect", "보호하다, 막다, 지키다, 비호하다"},
    {"protest", "단언하다"},
    {"proud", "뽐내는, 자랑하는 자긍하는, 영광으로 여기는"},
    {"prove", "시험하다, 실험하다, 경험하다, 시험해 보다"},
    {"provide", "준비하다, 미리 …에 대비하다  규정하다"},
    {"public", "심리, 심리 상태"},
    {"publish", "발표 하다, 널리 알리다"},
    {"punch", "주먹질, 펀치  힘, 활기"},
    {"punish", "벌하다, 응징하다, 처형하다"},
    {"pupil", "흔히 국민학교 중학교 학생"},
    {"purple", "자줏빛의  새빨간  제왕의"},
    {"purpose", "목적"},
    {"pursue", "쫓다, 추적하다, 몰다"},
    {"qualify", "자격을 부여하다"},
    {"quality", "질"},
    {"quite", "아주"},
    {"racial", "인종(상)의"},
    {"raise", "올리다"},
    {"random", "닥치는 대로의"},
    {"range", "줄"},
    {"rapid", "빠른"},
    {"rather", "오히려"},
    {"reach", "도착하다"},
    {"react", "반응을 나타내다"},
    {"realize", "깨닫다"},
    {"reason", "이성"},
    {"recall", "되부르다"},
    {"receipt", "수령"},
    {"receive", "받다"},
    {"recent", "최근의"},
    {"recipe", "조리법"},
    {"record", "기록하다"},
    {"recover", "되찾다"},
    {"recycle", "재생 이용하다"},
    {"reduce", "줄이다"},
    {"refer", "조회시키다"},
    {"reflect", "반사하다"},
    {"reform", "개정(개혁)하다"},
    {"refuse", "거절하다"},
    {"regard", "주목해서 보다"},
    {"region", "지방"},
    {"regret", "유감"},
    {"regular", "규칙적인"},
    {"reject", "거절하다"},
    {"relate", "이야기하다"},
    {"relax", "늦추다"},
    {"release", "도와주다"},
    {"relieve", "구출하다"},
    {"remain", "남다"},
    {"remark", "깨닫다"},
    {"remedy", "치료"},
    {"remind", "생각나게 하다"},
    {"remote", "먼"},
    {"remove", "옮기다"},
    {"repair", "수선(수정)하다"},
    {"repeat", "반복하다"},
    {"replace", "되돌려 놓다"},
    {"reply", "대답하다"},
    {"report", "보고"},
    {"request", "부탁하다"},
    {"require", "요구하다"},
    {"rescue", "구하다"},
    {"reserve", "따로 두다"},
    {"resist", "저항하다"},
    {"resolve", "분해하다"},
    {"resort", "(자주)가다"},
    {"respect", "존경하다"},
    {"respond", "대답하다"},
    {"restore", "반환하다"},
    {"result", "결과"},
    {"retire", "퇴직하다"},
    {"reveal", "나타내다"},
    {"review", "재조사"},
    {"revise", "교정하다"},
    {"revive", "소생하다"},
    {"reward", "보수"},
    {"rhythm", "율동"},
    {"rival", "경쟁자 경쟁하는 경쟁하다"},
    {"roast", "불에 쬐어 굽다 불고기 구운"},
    {"rough", "거친"},
    {"round", "둥근 원 돌아서"},
    {"route", "길"},
    {"routine", "정해진 일"},
    {"royal", "왕의"},
    {"rubber", "맛사지사"},
    {"rumor", "소문"},
    {"rural", "시골의"},
    {"sacred", "신성한"},
    {"salary", "봉급 봉급을 주다"},
    {"satisfy", "만족시키다"},
    {"scale", "비늘(모양의 것)"},
    {"scandal", "추문"},
    {"scare", "위협하다"},
    {"scene", "장면"},
    {"scheme", "계획"},
    {"scholar", "학자"},
    {"scold", "꾸짖다 잔소리 심한 사람"},
    {"scratch", "할퀴다, 할퀴어 상처 를 내다  긁다"},
    {"scream", "비명을 지르다"},
    {"screen", "병풍"},
    {"search", "찾다"},
    {"secret", "비밀의"},
    {"sector", "부채꼴"},
    {"secure", "안전한"},
    {"select", "고르다"},
    {"senior", "연상의"},
    {"sense", "감각"},
    {"series", "연속"},
    {"serious", "진지한"},
    {"serve", "섬기다"},
    {"session", "개회"},
    {"settle", "등받이가 높은 긴 의자 놓다"},
    {"several", "수개의"},
    {"severe", "호된"},
    {"shade", "그늘"},
    {"shadow", "그림자"},
    {"shake", "흔들어 움직이다"},
    {"shall", "-하겠다"},
    {"shallow", "얕은 얕은 곳 얕아지다"},
    {"shame", "부끄럼"},
    {"shape", "모양"},
    {"share", "몫"},
    {"sharp", "날카로운"},
    {"shave", "깎다"},
    {"sheep", "양"},
    {"sheet", "깔천"},
    {"shelf", "선반"},
    {"shell", "겉껍질"},
    {"shift", "옮기다"},
    {"shine", "빛나다"},
    {"shoot", "쏘다"},
    {"shore", "물가"},
    {"shout", "외치다"},
    {"shower", "소나기 빗발치듯 퍼붓다(쏟다)"},
    {"sight", "광경"},
    {"silent", "조용한"},
    {"silly", "어리석은 바보"},
    {"silver", "은"},
    {"similar", "유사한"},
    {"simple", "단일의"},
    {"since", "-이래"},
    {"single", "단 하나의"},
    {"skill", "숙련"},
    {"slave", "노예 노예처럼 일하다"},
    {"slice", "얇은조각"},
    {"slide", "미끄러지다"},
    {"smash", "박살내다"},
    {"smoke", "연기"},
    {"smooth", "매끄러운"},
    {"snake", "뱀"},
    {"social", "사회의"},
    {"society", "사회"},
    {"soldier", "군인"},
    {"solid", "고체의"},
    {"solve", "해결하다"},
    {"source", "원천"},
    {"spare", "여분의"},
    {"spark", "불꽃"},
    {"special", "특별한"},
    {"species", "종"},
    {"speech", "연설"},
    {"spell", "철자하다"},
    {"spend", "소비하다"},
    {"spirit", "정신"},
    {"spoil", "망쳐놓다"},
    {"spread", "펴다"},
    {"square", "정사각형의"},
    {"squeeze", "압착하다"},
    {"stable", "안정된"},
    {"stage", "무대"},
    {"stain", "더럽히다"},
    {"stairs", "계단"},
    {"stamp", "도장"},
    {"stare", "응시하다"},
    {"state", "상태"},
    {"station", "역"},
    {"statue", "조상"},
    {"status", "신분"},
    {"steady", "확고한"},
    {"steal", "훔치다"},
    {"steam", "증기"},
    {"steel", "강철"},
    {"stick", "나무토막"},
    {"still", "소리가 없는, 아직(도)"},
    {"stock", "줄기"},
    {"stomach", "위"},
    {"storm", "폭풍"},
    {"stove", "stave의 과거(분사)"},
    {"strange", "이상한"},
    {"straw", "짚"},
    {"stream", "시내"},
    {"stretch", "뻗치다"},
    {"strict", "엄중한"},
    {"strike", "치다"},
    {"string", "끈"},
    {"stripe", "줄무늬"},
    {"stuff", "재료"},
    {"subject", "복종시키다"},
    {"suburb", "교외"},
    {"succeed", "성공하다"},
    {"sudden", "별안간의"},
    {"suffer", "경험하다"},
    {"suggest", "암시하다"},
    {"suicide", "자살 자살하다"},
    {"summary", "요약"},
    {"summit", "꼭대기"},
    {"super", "임시고용배우"},
    {"superb", "장려한"},
    {"supply", "공급하다"},
    {"support", "지탱하다"},
    {"suppose", "상상하다"},
    {"surface", "표면"},
    {"surgery", "외과"},
    {"survey", "둘러보다"},
    {"survive", "살아 남다"},
    {"suspect", "짐작하다"},
    {"swallow", "삼키다"},
    {"sweat", "땀"},
    {"sweet", "단"},
    {"swing", "흔들리다"},
    {"switch", "회초리"},
    {"symbol", "상징"},
    {"symptom", "조짐"},
    {"system", "조직"},
    {"tackle", "고패"},
    {"talent", "재주"},
    {"target", "과녁"},
    {"tattoo", "귀영나팔"},
    {"teenage", "10대"},
    {"temple", "관자놀이"},
    {"tender", "제공"},
    {"tense", "시제"},
    {"theater", "극장"},
    {"theme", "논제"},
    {"theory", "이론"},
    {"thick", "두꺼운"},
    {"thief", "도둑"},
    {"though", "-임에도 불구하고 그러나"},
    {"threat", "협박"},
    {"thrill", "오싹하다 오싹함"},
    {"throat", "목"},
    {"through", "(-을)통하여 통하여 직통의"},
    {"throw", "던지다"},
    {"thumb", "엄지손가락 엄지손가락으로 만지다"},
    {"tight", "단단한"},
    {"tissue", "조직"},
    {"title", "표제"},
    {"tobacco", "담배"},
    {"toilet", "화장실"},
    {"tongue", "혀"},
    {"total", "총계 전체의 합계하다"},
    {"tough", "단단한"},
    {"toward", "-쪽으로"},
    {"toxic", "독의"},
    {"trace", "발자국"},
    {"trade", "매매"},
    {"traffic", "교통"},
    {"tragic", "비극의"},
    {"treat", "대우하다"},
    {"trend", "방향"},
    {"trial", "시험"},
    {"tribe", "종족"},
    {"trick", "책략"},
    {"triumph", "승리"},
    {"troop", "대"},
    {"trophy", "전리품"},
    {"trouble", "고생"},
    {"trouser", "즈봉"},
    {"trunk", "줄기"},
    {"trust", "신용"},
    {"truth", "진리"},
    {"tunnel", "터널"},
    {"tutor", "가정교사"},
    {"twist", "꼬이다"},
    {"typical", "전형적인"},
    {"uniform", "한결같은"},
    {"unify", "하나로 하다"},
    {"union", "결합"},
    {"unique", "유일무이한"},
    {"unite", "결합하다"},
    {"unless", "-하지 않으면"},
    {"until", "-까지"},
    {"update", "새롭게 하다 최신정보"},
    {"upper", "위쪽의"},
    {"upset", "뒤집어 엎다"},
    {"upward", "위로 향한"},
    {"urban", "도시의"},
    {"urgent", "긴급한"},
    {"usual", "평소의"},
    {"vacuum", "진공"},
    {"valley", "골짜기"},
    {"value", "가치"},
    {"various", "가지가지의"},
    {"vehicle", "운반 기구, 운송 수단,  수레, 차량, 탈것"},
    {"venture", "모험"},
    {"version", "번역, 번역문 개작, 각색, 번안"},
    {"versus", "…대, …에 대한"},
    {"victim", "희생, 산 제물, 인신 제물"},
    {"victory", "승리, 전승"},
    {"village", "마을, 촌락"},
    {"violent", "격렬한, 맹렬한"},
    {"visible", "눈에 보이는,  볼 수 있는"},
    {"visual", "시각의, 물건을 보기 위한"},
    {"volume", "책 권"},
    {"voyage", "여행"},
    {"waste", "낭비하다"},
    {"wealth", "재산"},
    {"weapon", "무기"},
    {"weigh", "무게를 달다"},
    {"weird", "불가사의한"},
    {"welfare", "행복"},
    {"whale", "고래"},
    {"wheat", "밀"},
    {"wheel", "바퀴"},
    {"whether", "-인지 어떤지"},
    {"which", "어느 쪽"},
    {"while", "동안 -하는 동안"},
    {"whisper", "속삭이다"},
    {"whistle", "휘파람"},
    {"whole", "전체의"},
    {"within", "-의 안쪽에 안으로 내부"},
    {"without", "-없이 밖은"},
    {"witness", "증언"},
    {"wonder", "경이"},
    {"worship", "숭배"},
    {"worth", "가치가 있는 가치"},
    {"would", "will의 과거"},
    {"wound", "부상"}
};

int nWord = sizeof(Words) / (sizeof(char*) * 2);
